In [2]:
import numpy as np

In [3]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
d = np.dot(a, b)

In [4]:
print (a)
print (b)
print (c)
print (d)

[[-0.10914631  1.40181183 -0.7075345 ]
 [-1.13894485 -0.70754562  0.96579786]
 [-0.97137971 -1.8193373  -0.36362527]]
[[-0.8212037 ]
 [-0.32641899]
 [-0.31990377]]
[[ 0.08963135 -1.15117306  0.58102995]
 [ 0.37177323  0.23095633 -0.31525476]
 [ 0.31074803  0.58201287  0.1163251 ]]
[[-0.14160369]
 [ 0.85729968]
 [ 1.50789195]]


In [6]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
#c = a*b

In [ ]:
e = np.random.randn(2,3,4)
print (e)
ee = e.reshape(2*3*4,1)
print (ee)

In [ ]:
a = [2,3,4]
print (type(a))
print (np.shape(a))
b = np.array(a)
print (type(b))
print (np.shape(b))

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])